name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  json_annotation: '^4.0.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^4.1.0'
  test: 'any'
